<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="3" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-09-06T18:25:27 CST" name="Default suite" finished-at="2024-09-06T18:25:59 CST" duration-ms="32819">
    <groups>
    </groups>
    <test started-at="2024-09-06T18:25:27 CST" name="Default test" finished-at="2024-09-06T18:25:59 CST" duration-ms="32819">
      <class name="Test.DesignExtentReport">
        <test-method is-config="true" signature="beforeTest()[pri:0, instance:Test.DesignExtentReport@7f485fda]" started-at="2024-09-06T18:25:27 CST" name="beforeTest" finished-at="2024-09-06T18:25:30 CST" duration-ms="3723" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method signature="Home()[pri:1, instance:Test.DesignExtentReport@7f485fda]" started-at="2024-09-06T18:25:30 CST" name="Home" finished-at="2024-09-06T18:25:56 CST" duration-ms="25179" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Home -->
        <test-method signature="DropDown()[pri:2, instance:Test.DesignExtentReport@7f485fda]" started-at="2024-09-06T18:25:56 CST" name="DropDown" finished-at="2024-09-06T18:25:57 CST" duration-ms="1656" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- DropDown -->
        <test-method signature="Destination()[pri:3, instance:Test.DesignExtentReport@7f485fda]" started-at="2024-09-06T18:25:57 CST" name="Destination" finished-at="2024-09-06T18:25:58 CST" duration-ms="1179" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Destination -->
        <test-method signature="failMethod()[pri:4, instance:Test.DesignExtentReport@7f485fda]" started-at="2024-09-06T18:25:58 CST" name="failMethod" finished-at="2024-09-06T18:25:58 CST" duration-ms="32" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at Test.DesignExtentReport.failMethod(DesignExtentReport.java:89)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failMethod -->
        <test-method is-config="true" signature="afterTest()[pri:0, instance:Test.DesignExtentReport@7f485fda]" started-at="2024-09-06T18:25:59 CST" name="afterTest" finished-at="2024-09-06T18:25:59 CST" duration-ms="922" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
      </class> <!-- Test.DesignExtentReport -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
